
sudo: required

language: java

services:
  - docker

install:
  - ls -l
  - mvn clean install -DskipTests
  - mvn test

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  skip_cleanup: true
  script: 
    - docker images ls -a
    - docker build -t atum-mysql-image -f build/Dockerfile.mysql .
    - docker build -t atum-tomcat-image -f build/Dockerfile.tomcat .
    - docker push atum
    - docker images ls -a
  on:
    branch: master

after_deploy:

cache:
  directories:
  - $HOME/.m2