sudo: required

language: java

env:
  global:
     - BRANCH=${TRAVIS_BRANCH}
     - TAG=${TRAVIS_COMMIT::6}
     - PREPROD_APP_NAME=atum-preprod
     - PROD_APP_NAME=atum-prod

services:
  - docker

install:
  - mvn clean install -DskipTests

script:
  - echo "Running tests..."
  - mvn test

after_success:
  - docker --version
  - docker login --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com
  - echo "Building atum-tomcat image..."
  - docker build -t atum-tomcat:$BRANCH-$TAG -f build/Dockerfile.tomcat .
  - docker tag atum-tomcat:$BRANCH-$TAG registry.heroku.com/${PREPROD_APP_NAME}/web
  - docker push registry.heroku.com/${PREPROD_APP_NAME}/web
  
before_deploy:
  - echo "Nothing in before_deploy"

# deploy:
#  provider: heroku
#  api_key:
#    secure: 
#  app: atum-preprod

after_deploy:
  - echo "Nothing in after_deploy"

cache:
  directories:
  - $HOME/.m2