sudo: required

language: java

env:
  global:
     - BRANCH=${TRAVIS_BRANCH}
     #- TAG=${TRAVIS_COMMIT::6}
     - TAG=latest
     - PREPROD_APP_NAME=atum-preprod
     - PROD_APP_NAME=atum-prod

services:
  - docker

install:
  - mvn clean install -DskipTests

script:
  - echo "Running tests..."
  - mvn test

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t atum-mysql:$BRANCH-$TAG -f build/Dockerfile.mysql .
  - docker tag atum-mysql:$BRANCH-$TAG vaibhavdesai137/atum-mysql:$BRANCH-$TAG
  - docker push vaibhavdesai137/atum-mysql
  - docker build -t atum-tomcat:$BRANCH-$TAG -f build/Dockerfile.tomcat .
  - docker tag atum-tomcat:$BRANCH-$TAG vaibhavdesai137/atum-tomcat:$BRANCH-$TAG
  - docker push vaibhavdesai137/atum-tomcat
  
before_deploy:
  - echo "Nothing in before_deploy"

# deploy:
#  provider: heroku
#  api_key:
#    secure: 
#  app: atum-preprod

after_deploy:
  - echo "Nothing in after_deploy"

cache:
  directories:
  - $HOME/.m2