
sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t atum-mysql-image -f Dockerfile.mysql .
  - docker build -t atum-tomcat-image -f Dockerfile.tomcat .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push vaibhavdesai137/atum
  - docker network create atum-network
  - docker run --net atum-network -p 3306:3306 --name atum-mysql -d atum-mysql-image
  - docker ps -a
  - docker run --net atum-network -p 8080:8080 --name atum-tomcat -d atum-tomcat-image

script:
  - bundle exec rake test