
sudo: required

language: java

services:
  - docker

install:
  - ls -l
  - mvn clean install -DskipTests
  - docker build -t atum-mysql-image -f build/Dockerfile.mysql .
  - docker build -t atum-tomcat-image -f build/Dockerfile.tomcat .
  
after_install:
  skip_cleanup: true

after_install:
  - docker images ls -a

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  #- docker login --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com

deploy:
  provider: script
  script: docker push atum
  on:
    branch: master

after_deploy:

cache:
  directories:
  - $HOME/.m2