sudo: required

language: java

env:
  global:
     - TAG=${TRAVIS_COMMIT::6}

services:
  - docker

install:
  - mvn clean install -DskipTests

script:
  - echo "Running tests..."
  - mvn test

after_success:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker images ls -a
  - docker build -t atum-mysql-image:$TAG -f build/Dockerfile.mysql .
  - docker build -t atum-tomcat-image:$TAG -f build/Dockerfile.tomcat .
  - docker push atum
  - docker images ls -a
  
before_deploy:
  - echo "Nothing in before_deploy"

after_deploy:
  - echo "Nothing in after_deploy"

cache:
  directories:
  - $HOME/.m2